- name: Get Service Status
  hosts: all
  gather_facts: no

  tasks:
    - name: Check Service Status
      win_shell: Get-Service | Where-Object { $_.DisplayName -eq "Every Angle Application Server" } | Select-Object DisplayName, Status
      register: service_status

    - name: Print Service Status
      debug:
        var: service_status.stdout_lines