---
- name: Manage Application Server
  hosts: all
  gather_facts: no
  tasks:
    - name: Check Service Status
      win_shell: Get-Service | Where-Object { $_.DisplayName -eq "Every Angle Application Server" } | Select-Object DisplayName, Status
      register: service_status

    - name: Print Service Status
      debug:
        var: service_status.stdout_lines
        
    - name: Read Configuration File
      win_shell: |
        $configFile = "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config"
        $configContent = [System.IO.File]::ReadAllText($configFile)
        $logFolderPattern = '<add key="LogFolder" value="([^"]+)"'
        $logFolderMatch = [regex]::Match($configContent, $logFolderPattern)
        
        if ($logFolderMatch.Success) {
          $logFolderValue = $logFolderMatch.Groups[1].Value
          Write-Host "LogFolder Value: $logFolderValue"
        } else {
          Write-Host "LogFolder Not Found in Configuration"
        }
      register: result
    - debug:
        var: result.stdout_lines

    - name: Stop Service from Services.msc
      win_service:
        name: Every Angle Application Server
        state: stopped
      register: stop_service_result
    - debug:
        var: stop_service_result.stdout_lines

    - name: Check if Service is Running
      win_shell: Get-Service -Name "Every Angle Application Server" | Select-Object -ExpandProperty Status
      register: service_status_before

    - name: Move Log File
      win_shell: |
        $logFilePath = "F:\Data\AppServer\log\AppServerInstall.log"
        $newLogFolderPath = "F:\Data\AppServer\log\log-test"
        if (-not (Test-Path $logFilePath -PathType Leaf)) {
          Write-Host "Log file does not exist in the source location."
        } else {
          if (-not (Test-Path $newLogFolderPath -PathType Container)) {
            New-Item -Path $newLogFolderPath -ItemType Directory
          }
          Move-Item -Path $logFilePath -Destination $newLogFolderPath
        }
      register: move_log_result
      ignore_errors: yes
    - debug:
        var: move_log_result.stdout_lines

    - name: Update LogFolder
      win_shell: |
        $configFile = "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config"
        $newLogFolderPath = "F:\Data\AppServer\log\log-test"
        [xml]$config = Get-Content $configFile
        $logFolderNode = $config.configuration.appSettings.add | Where-Object { $_.key -eq "LogFolder" }
        if ($logFolderNode -ne $null) {
          $logFolderNode.value = $newLogFolderPath
          $config.Save($configFile)
        }
      register: update_log_folder_result
      ignore_errors: yes

    - name: Read changed Log File Location
      win_shell: |
        $configFile = "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config"
        $configContent = [System.IO.File]::ReadAllText($configFile)
        $logFolderPattern = '<add key="LogFolder" value="([^"]+)"'
        $logFolderMatch = [regex]::Match($configContent, $logFolderPattern)
        
        if ($logFolderMatch.Success) {
          $logFolderValue = $logFolderMatch.Groups[1].Value
          Write-Host "LogFolder Value: $logFolderValue"
        } else {
          Write-Host "LogFolder Not Found in Configuration"
        }
      register: result
      ignore_errors: yes
    - debug:
        var: result.stdout_lines

    - name: Start Service
      win_service:
        name: Every Angle Application Server
        state: started
      register: start_service_result

    - name: Check Service Status
      win_shell: Get-Service -Name "Every Angle Application Server" | Select-Object -ExpandProperty Status
      register: service_status_after

    - name: Print Service Status Before
      debug:
        var: service_status_before.stdout

    - name: Print Service Status After
      debug:
        var: service_status_after.stdout


    