- name: Get Service Status
  hosts: all
  gather_facts: no

  tasks:
    - name: Check Service Status
      win_shell: Get-Service | Where-Object { $_.DisplayName -eq "Every Angle Application Server" } | Select-Object DisplayName, Status
      register: service_status

    - name: Print Service Status
      debug:
        var: service_status.stdout_lines
        
    - name: Read Configuration File
      win_shell: |
        $configFile = "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config"
        $configContent = [System.IO.File]::ReadAllText($configFile)
        $logFolderPattern = '<add key="LogFolder" value="([^"]+)"'
        $logFolderMatch = [regex]::Match($configContent, $logFolderPattern)
        
        if ($logFolderMatch.Success) {
          $logFolderValue = $logFolderMatch.Groups[1].Value
          Write-Host "LogFolder Value: $logFolderValue"
        } else {
          Write-Host "LogFolder Not Found in Configuration"
        }
      register: result
    - debug:
        var: result.stdout_lines