---
- name: Get Service Status and LogFolder
  hosts: all
  gather_facts: no

  tasks:
    - name: Check Service Status
      win_shell: Get-Service | Where-Object { $_.DisplayName -eq "Every Angle Application Server" } | Select-Object DisplayName, Status
      register: service_status

    - name: Retrieve LogFolder from Config File
      win_shell: Get-Content "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config" -Raw
      register: config_content

    - name: Extract LogFolder Value
      set_fact:
        log_folder_value: "{{ config_content.stdout | regex_search('<add key=\"LogFolder\" value=\"(.+?)\" />').match(1) }}"
      ignore_errors: yes  # Ignore errors if the key is not found

    - name: Print Service Status and LogFolder
      debug:
        var: 
          - service_status
          - log_folder_value
