---
- name: Get Service Status and LogFolder
  hosts: all
  gather_facts: no

  tasks:
    - name: Check Service Status
      win_shell: Get-Service | Where-Object { $_.DisplayName -eq "Every Angle Application Server" } | Select-Object DisplayName, Status
      register: service_status

    - name: Read Configuration File
      win_shell: |
        [xml]$config = Get-Content "F:\Apps\AppServer\EveryAngle.Edgar.Service.exe.config"
        $logFolder = $config.configuration.appSettings.add | Where-Object { $_.key -eq "LogFolder" }
        if ($logFolder -ne $null) {
          $logFolderValue = $logFolder.value.Replace('\\\\', '\\')
          Write-Host "LogFolder Value: $logFolderValue"
        } else {
          Write-Host "LogFolder Not Found in Configuration"
        }
      register: result

    - name: Print Service Status and LogFolder
      debug:
        var: 
          - service_status
          - result.stdout_lines
