---
- name: Check Python and Ansible Installation and Use Ansible Galaxy Task
  hosts: all    # Replace with the name of your Windows EC2 group or host(s)
  gather_facts: false
  tasks:
    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      ignore_errors: yes  # Ignore errors if the directory already exists

    - name: Check if Python is Installed
      ansible.windows.win_command: 'where python'
      register: python_check_result
      ignore_errors: no  # Ignore errors if 'where python' command fails

    - name: Install Python if not installed
      ansible.windows.win_command: 'C:\Temp\python-3.9.7-amd64.exe /quiet InstallAllUsers=1 PrependPath=1'
      when: "'INFO: Could not find files for the given pattern(s).' in python_check_result.stderr_lines"
      ignore_errors: no
      register: python_install_output

    - name: Display Python Installation Output
      debug:
        var: python_install_output.stdout_lines

    - name: Check if Ansible is Installed
      ansible.windows.win_command: 'where ansible'
      register: ansible_check_result
      ignore_errors: yes  # Ignore errors if 'where ansible' command fails

    - name: Install Ansible if not installed
      ansible.windows.win_command: 'C:\Program Files\Python39\Scripts\pip3.9.exe install ansible'
      when: "'INFO: Could not find files for the given pattern(s).' in ansible_check_result.stderr_lines"
      ignore_errors: no
      register: ansible_install_output

    - name: Display Ansible Installation Output
      debug:
        var: ansible_install_output.stdout_lines

    - name: Set PATH to include Ansible
      ansible.windows.win_environment:
        name: PATH
        value: '{{ ansible_env.PATH }};C:\Program Files\Python39\Scripts'
      when: ansible_install_output.rc == 0  # Only run if Ansible is installed

    - name: Install Ansible Galaxy Collections
      ansible.windows.win_shell: ansible-galaxy collection install community.general
      when: ansible_install_output.rc == 0  # Only run if Ansible is installed
      register: galaxy_install_output

    - name: Display Ansible Galaxy Installation Output
      debug:
        var: galaxy_install_output.stdout_lines

    # Add your Datadog API task or any other tasks here

    # Cleanup the Python installer (optional)
    - name: Remove Python Installer
      ansible.windows.win_shell: Remove-Item -Path "C:\Temp\python-3.9.7-amd64.exe" -Force
      when: python_install_output.failed == false and python_check_result.rc != 0
