---
- name: Retrieve and Transfer Logs from AWX to Server
  hosts: localhost
  gather_facts: false
  vars:
    # Replace these with your AWX API credentials and server information
    awx_base_url: "http://awx.iswcloudapp.com/"
    awx_username: "admin"
    awx_password: "M@inak@2310"
    job_id: "your-job-id"
    server_ip: "172.31.24.128"
    server_user: "Administrator"
    server_destination: "/home/ec2-user/awx-log"

  tasks:
    - name: Fetch AWX job log
      uri:
        url: "{{ awx_base_url }}/api/v2/jobs/{{ job_id }}/stdout/?format=txt"
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
      register: job_log

    - name: Transfer log to the server
      ansible.builtin.scp:
        src: "{{ job_log.content }}"
        dest: "{{ server_user }}@{{ server_ip }}:{{ server_destination }}awx_job_log.txt"
