---
- name: PowerShell Getting Started First Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        error_action: stop
        script: |
          Write-Output "Hello World"
