---
- name: PowerShell Getting Started First Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_command: powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Write-Output 'Hello World'"
      register: powershell_output

    - name: Display PowerShell output
      debug:
        var: powershell_output.stdout_lines
