---
- name: Run PowerShell Script
  hosts: all  # Replace with the name of your target host group or use 'all' to target all hosts
  gather_facts: no

  tasks:
    - name: Execute PowerShell Script
      ansible.windows.win_command: powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File C:/EASetups/powershellscripts/content.ps1
      register: ps_script_output

    - name: Display PowerShell Script Output
      debug:
        var: ps_script_output.stdout_lines
