---
- name: Check Python and Ansible Installation and Use Ansible Galaxy Task
  hosts: all 
  become: yes
  become_method: runas
  become_user: Administrator 
  gather_facts: false
  tasks:
    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Ansible-Logs
        state: directory
      ignore_errors: yes
      
    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      ignore_errors: yes  # Ignore errors if the directory already exists

    - name: Check if Python is Installed
      ansible.windows.win_command: 'where python'
      register: python_check_result
      ignore_errors: yes  # Ignore errors if 'where python' command fails

    - name: Install Python if not installed
      ansible.windows.win_shell: |
        $url = "https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe"
        $outputFile = "C:\Temp\python-3.8.10-amd64.exe"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
        Start-Process -Wait -FilePath $outputFile -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1"
      when: "'INFO: Could not find files for the given pattern(s).' in python_check_result.stderr_lines"
      environment:
        PATH: "C:\Program Files\Python38"
      ignore_errors: no
      register: python_install_output

     # Cleanup the Python installer (optional)
    - name: Remove Python Installer
      ansible.windows.win_shell: Remove-Item -Path "C:\Temp\python-3.9.7-amd64.exe" -Force
      when: python_install_output.failed == false and python_check_result.rc != 0

    