- name: Check Python and Ansible Installation and Use Ansible Galaxy Task
  hosts: all    # Replace with the name of your Windows EC2 group or host(s)
  become: yes
  become_method: runas
  become_user: Administrator
  gather_facts: false
  tasks:
    - name: Display Message Before Creating Destination Folder
      debug:
        msg: "Creating the destination folder for Python Installer."

    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      ignore_errors: yes

    - name: Display Message After Creating Destination Folder
      debug:
        msg: "Destination folder for Python Installer has been created."

    # Add tasks here to perform actions in Account B using the temporary credentials.
