- name: Install Datadog Agent if not already installed
  hosts: all
  tasks:
    - name: Execute PowerShell to get datadog api key
      ansible.windows.win_shell: |
        $secretName = "DataDog_API_Key"
        $secret = Get-SECSecretValue -SecretId $secretName
        $apiKey = ConvertFrom-Json $secret.SecretString | Select-Object -ExpandProperty DataDog_API_Key
        $apiKeyFilePath = "C:\datadog_api.txt"
        $apiKey | Set-Content -Path $apiKeyFilePath
      register: retrieve_output
      ignore_errors: no

    - name: Get DataDog API Key from the file
      win_shell: Get-Content "C:\\datadog_api.txt"
      register: api_key_result 
      ignore_errors: no   

    - name: Extract API Key from the output
      set_fact:
        api_key: "{{ api_key_result.stdout | regex_replace('\\r\\n$', '') | split('\n') | first }}"

    
    - name: API_KEY
      debug:
        var: api_key


    - name: Install Datadog Agent with extracted API Key
  win_shell: "msiexec.exe /i C:\\Temp\\datadog-agent-7-latest.amd64.msi /quiet APIKEY={{ api_key }}"
