- name: Install Datadog Agent if not already installed
  hosts: all
  tasks:
    - name: Get DataDog API Key from AWS Secrets Manager
      aws_secretsmanager:
        secret_id: DataDog_API_Key
      register: secret_result
    
    - name: Display the output
      debug:
        var: secret_result