- name: Install Datadog Agent if not already installed
  hosts: all
  tasks:
    - name: Execute PowerShell Script
      ansible.windows.win_shell: |
        $secretName = "DataDog_API_Key"
        $secret = Get-SECSecretValue -SecretId $secretName
        $apiKey = ConvertFrom-Json $secret.SecretString | Select-Object -ExpandProperty DataDog_API_Key
        $apiKeyFilePath = "C:\datadog_api.txt"
        $apiKey | Set-Content -Path $apiKeyFilePath
      register: retrieve_output
    - name: Display the retrieve_output
      debug:
        var: retrieve_output

    - name: Get DataDog API Key from the file
      win_shell: Get-Content "C:\\datadog_api.txt"
      register: api_key_result    
      
    - name: Display the output
      debug:
        var: api_key_result
    
    - name: Extract API Key from the output
      set_fact:
        api_key: "{{ api_key_result.stdout | json_query('0') }}"
    
    - name: API_KEY
      debug:
        var: api_key