---
- name: PowerShell Getting Started First Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_command: powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Write-Output 'Hello World'"
      register: powershell_output

    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Ansible-Logs
        state: directory
      ignore_errors: yes 

    - name: Store PowerShell output in a file
      copy:
        content: "{{ powershell_output.stdout_lines | join('\n') }}"
        dest: "C:\Ansible-Logs\output_{{ ansible_run_id }}.txt"
        remote_src: yes
        append: yes

    - name: Run Python HTTP Server
      win_shell: |
        python -c "import http.server, socketserver
        class CustomHandler(http.server.SimpleHTTPRequestHandler):
            def do_GET(self):
                if self.path == '/':
                    with open('C:/Ansible-Logs/output.txt', 'r') as file:
                        output_content = file.read()
                    self.send_response(200)
                    self.send_header('Content-type', 'text/html')
                    self.end_headers()
                    self.wfile.write(output_content.encode('utf-8'))
                else:
                    super().do_GET()
        port = 8080
        with socketserver.TCPServer(('', port), CustomHandler) as httpd:
            httpd.serve_forever()"
      async: true
