- name: Check Python and Ansible Installation and Use Ansible Galaxy Task
  hosts: all    # Replace with the name of your Windows EC2 group or host(s)
  become: yes
  become_method: runas
  become_user: Administrator
  gather_facts: false
  tasks:
    - name: Display Message Before Creating Destination Folder
      debug:
        msg: "Creating the destination folder for Python Installer."

    - name: Create Destination Folder for Python Installer
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      ignore_errors: yes

    - name: Display Message After Creating Destination Folder
      debug:
        msg: "Destination folder for Python Installer has been created."

    # Add tasks here to perform actions in Account B using the temporary credentials.
---


    - name: Install Ansible Galaxy Collections
      ansible.windows.win_shell: |
        $env:PATH = "C:\Program Files\Python39;$env:PATH"
        ansible-galaxy collection install community.general
      when: ansible_check_result.rc == 0  # Only run if Ansible is installed successfully
      register: galaxy_install_output

    - name: Display Ansible Galaxy Installation Output
      debug:
        var: galaxy_install_output.stdout_lines

    # Add your Datadog API task or any other tasks here

    # Cleanup the Python installer (optional)
    - name: Remove Python Installer
      ansible.windows.win_shell: Remove-Item -Path "C:\Temp\python-3.9.7-amd64.exe" -Force
      when: python_install_output.failed == false and python_check_result.rc != 0
